server:
  port: 8001

spring:
  jpa:
    properties:
      hibernate:
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddlAuto: update
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

  datasource:
    url: jdbc:postgresql://192.168.15.64:5432/dukescode
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
